# cmake/convert_binary_to_array.cmake
# CMake script-mode (-P) replacement for contrib/Orochi/scripts/convert_binary_to_array.py
#
# Expected variables (passed via -D):
#   INPUT_FILE              — path to the original (uncompressed) binary
#   COMPRESSED_FILE         — path to the compressed binary (or same as INPUT_FILE when no compression)
#   OUTPUT_HEADER           — path to the output .h file
#   COMPRESSION_ACTIVATED   — ON or OFF

cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED INPUT_FILE OR NOT DEFINED COMPRESSED_FILE OR NOT DEFINED OUTPUT_HEADER OR NOT DEFINED COMPRESSION_ACTIVATED)
    message(FATAL_ERROR "convert_binary_to_array.cmake: INPUT_FILE, COMPRESSED_FILE, OUTPUT_HEADER, and COMPRESSION_ACTIVATED must be defined")
endif()

# Determine which file to embed
if(COMPRESSION_ACTIVATED)
    set(_bin_file "${COMPRESSED_FILE}")
else()
    set(_bin_file "${INPUT_FILE}")
endif()

# Read the binary file as hex
file(READ "${_bin_file}" _hex HEX)
string(LENGTH "${_hex}" _hex_len)
math(EXPR _byte_count "${_hex_len} / 2")

# Get uncompressed size
file(SIZE "${INPUT_FILE}" _uncompressed_size)

# Derive array name from the output header filename
get_filename_component(_header_name "${OUTPUT_HEADER}" NAME)
string(REPLACE "." "_" _array_name "${_header_name}")

# Convert hex string to comma-separated 0x.. values
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " _hex_array "${_hex}")

# Build the C header content
set(_content "// generated by convert_binary_to_array.cmake\n")
if(COMPRESSION_ACTIVATED)
    string(APPEND _content "// Data is compressed.\n")
endif()
string(APPEND _content "const unsigned char ${_array_name}[] = {\n    ${_hex_array}\n};\n")
string(APPEND _content "const size_t ${_array_name}_size = sizeof(${_array_name}); // ${_byte_count}\n")

if(COMPRESSION_ACTIVATED)
    string(APPEND _content "const size_t ${_array_name}_size_uncompressed = ${_uncompressed_size}; // size of the data in bytes, once it has been uncompressed.\n")
else()
    string(APPEND _content "const size_t ${_array_name}_size_uncompressed = ${_array_name}_size; // same than raw buffer, because data is not compressed.\n")
endif()

if(COMPRESSION_ACTIVATED)
    string(APPEND _content "const bool   ${_array_name}_isCompressed = true;\n")
else()
    string(APPEND _content "const bool   ${_array_name}_isCompressed = false;\n")
endif()

file(WRITE "${OUTPUT_HEADER}" "${_content}")
message(STATUS "convert_binary_to_array: ${OUTPUT_HEADER} (${_byte_count} bytes)")
